//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCopPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Macro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Macro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCopPlus.Properties.Macro", typeof(Macro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AnyCode {
            get {
                return ResourceManager.GetString("AnyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (any character sequence).
        /// </summary>
        internal static string AnyDescription {
            get {
                return ResourceManager.GetString("AnyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .+.
        /// </summary>
        internal static string AnyRegular {
            get {
                return ResourceManager.GetString("AnyRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AnySample {
            get {
                return ResourceManager.GetString("AnySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaBb.
        /// </summary>
        internal static string CamelCode {
            get {
                return ResourceManager.GetString("CamelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camelNamingStyle.
        /// </summary>
        internal static string CamelDescription {
            get {
                return ResourceManager.GetString("CamelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOWER+((UPPERLOWER+)EXTENSION)*.
        /// </summary>
        internal static string CamelRegular {
            get {
                return ResourceManager.GetString("CamelRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sampleName.
        /// </summary>
        internal static string CamelSample {
            get {
                return ResourceManager.GetString("CamelSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aa_Bb.
        /// </summary>
        internal static string CapitalizedCode {
            get {
                return ResourceManager.GetString("CapitalizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All_Words_Capitalized.
        /// </summary>
        internal static string CapitalizedDescription {
            get {
                return ResourceManager.GetString("CapitalizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((UPPERLOWER+)EXTENSION|DIGIT+)(_((UPPERLOWER+)EXTENSION|DIGIT+))*|UPPER.
        /// </summary>
        internal static string CapitalizedRegular {
            get {
                return ResourceManager.GetString("CapitalizedRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample_Name.
        /// </summary>
        internal static string CapitalizedSample {
            get {
                return ResourceManager.GetString("CapitalizedSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aabb.
        /// </summary>
        internal static string LowerOnlyCode {
            get {
                return ResourceManager.GetString("LowerOnlyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lowercaseonly.
        /// </summary>
        internal static string LowerOnlyDescription {
            get {
                return ResourceManager.GetString("LowerOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOWER+.
        /// </summary>
        internal static string LowerOnlyRegular {
            get {
                return ResourceManager.GetString("LowerOnlyRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samplename.
        /// </summary>
        internal static string LowerOnlySample {
            get {
                return ResourceManager.GetString("LowerOnlySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string LowerSingleCode {
            get {
                return ResourceManager.GetString("LowerSingleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (single lower character).
        /// </summary>
        internal static string LowerSingleDescription {
            get {
                return ResourceManager.GetString("LowerSingleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOWER.
        /// </summary>
        internal static string LowerSingleRegular {
            get {
                return ResourceManager.GetString("LowerSingleRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string LowerSingleSample {
            get {
                return ResourceManager.GetString("LowerSingleSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa_bb.
        /// </summary>
        internal static string LowerWordsCode {
            get {
                return ResourceManager.GetString("LowerWordsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all_words_lowercase.
        /// </summary>
        internal static string LowerWordsDescription {
            get {
                return ResourceManager.GetString("LowerWordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOWER+(_LOWER+)*.
        /// </summary>
        internal static string LowerWordsRegular {
            get {
                return ResourceManager.GetString("LowerWordsRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sample_name.
        /// </summary>
        internal static string LowerWordsSample {
            get {
                return ResourceManager.GetString("LowerWordsSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AaBb.
        /// </summary>
        internal static string PascalCode {
            get {
                return ResourceManager.GetString("PascalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PascalNamingStyle.
        /// </summary>
        internal static string PascalDescription {
            get {
                return ResourceManager.GetString("PascalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((UPPERLOWER+)EXTENSION|DIGIT+)+|UPPER.
        /// </summary>
        internal static string PascalRegular {
            get {
                return ResourceManager.GetString("PascalRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleName.
        /// </summary>
        internal static string PascalSample {
            get {
                return ResourceManager.GetString("PascalSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AABB.
        /// </summary>
        internal static string UpperOnlyCode {
            get {
                return ResourceManager.GetString("UpperOnlyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPERCASEONLY.
        /// </summary>
        internal static string UpperOnlyDescription {
            get {
                return ResourceManager.GetString("UpperOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER+.
        /// </summary>
        internal static string UpperOnlyRegular {
            get {
                return ResourceManager.GetString("UpperOnlyRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMPLENAME.
        /// </summary>
        internal static string UpperOnlySample {
            get {
                return ResourceManager.GetString("UpperOnlySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string UpperSingleCode {
            get {
                return ResourceManager.GetString("UpperSingleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (single upper character).
        /// </summary>
        internal static string UpperSingleDescription {
            get {
                return ResourceManager.GetString("UpperSingleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER.
        /// </summary>
        internal static string UpperSingleRegular {
            get {
                return ResourceManager.GetString("UpperSingleRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string UpperSingleSample {
            get {
                return ResourceManager.GetString("UpperSingleSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA_BB.
        /// </summary>
        internal static string UpperWordsCode {
            get {
                return ResourceManager.GetString("UpperWordsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL_WORDS_UPPERCASE.
        /// </summary>
        internal static string UpperWordsDescription {
            get {
                return ResourceManager.GetString("UpperWordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPER+(_UPPER+)*.
        /// </summary>
        internal static string UpperWordsRegular {
            get {
                return ResourceManager.GetString("UpperWordsRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMPLE_NAME.
        /// </summary>
        internal static string UpperWordsSample {
            get {
                return ResourceManager.GetString("UpperWordsSample", resourceCulture);
            }
        }
    }
}
