//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCopPlus.Plugin.MoreCustom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomRulesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomRulesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCopPlus.Plugin.MoreCustom.Rules.CustomRulesResources", typeof(CustomRulesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (tabs x{1}).
        /// </summary>
        internal static string CharLimitOptionsFormat {
            get {
                return ResourceManager.GetString("CharLimitOptionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates the spacing at the end of the each code line..
        /// </summary>
        internal static string DescriptionSP2000 {
            get {
                return ResourceManager.GetString("DescriptionSP2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks characters used for indentation..
        /// </summary>
        internal static string DescriptionSP2001 {
            get {
                return ResourceManager.GetString("DescriptionSP2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether last code line is empty or not..
        /// </summary>
        internal static string DescriptionSP2002 {
            get {
                return ResourceManager.GetString("DescriptionSP2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates that code line is not longer than specified characters count..
        /// </summary>
        internal static string DescriptionSP2100 {
            get {
                return ResourceManager.GetString("DescriptionSP2100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates that method body does not contain more code lines than specified..
        /// </summary>
        internal static string DescriptionSP2101 {
            get {
                return ResourceManager.GetString("DescriptionSP2101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates that property body does not contain more code lines than specified..
        /// </summary>
        internal static string DescriptionSP2102 {
            get {
                return ResourceManager.GetString("DescriptionSP2102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates that source file does not contain more code lines than specified..
        /// </summary>
        internal static string DescriptionSP2103 {
            get {
                return ResourceManager.GetString("DescriptionSP2103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stylecopplus.codeplex.com/wikipage?title={0}.
        /// </summary>
        internal static string DetailsUrl {
            get {
                return ResourceManager.GetString("DetailsUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2000 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2001 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2002 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2100 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2101 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2102 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExampleSP2103 {
            get {
                object obj = ResourceManager.GetObject("ExampleSP2103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use different indendation characters within one code line..
        /// </summary>
        internal static string IndentContextBoth {
            get {
                return ResourceManager.GetString("IndentContextBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only space characters are allowed to be used for indentation..
        /// </summary>
        internal static string IndentContextSpaces {
            get {
                return ResourceManager.GetString("IndentContextSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only tab characters are allowed to be used for indentation..
        /// </summary>
        internal static string IndentContextTabs {
            get {
                return ResourceManager.GetString("IndentContextTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs and spaces.
        /// </summary>
        internal static string IndentOptionsBoth {
            get {
                return ResourceManager.GetString("IndentOptionsBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (allow padding).
        /// </summary>
        internal static string IndentOptionsPaddingFormat {
            get {
                return ResourceManager.GetString("IndentOptionsPaddingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces only.
        /// </summary>
        internal static string IndentOptionsSpaces {
            get {
                return ResourceManager.GetString("IndentOptionsSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs only.
        /// </summary>
        internal static string IndentOptionsTabs {
            get {
                return ResourceManager.GetString("IndentOptionsTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should always.
        /// </summary>
        internal static string LastLineContextEmpty {
            get {
                return ResourceManager.GetString("LastLineContextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not.
        /// </summary>
        internal static string LastLineContextNotEmpty {
            get {
                return ResourceManager.GetString("LastLineContextNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string LastLineOptionsEmpty {
            get {
                return ResourceManager.GetString("LastLineOptionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not empty.
        /// </summary>
        internal static string LastLineOptionsNotEmpty {
            get {
                return ResourceManager.GetString("LastLineOptionsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max character limit:.
        /// </summary>
        internal static string LimitOptionsCharDescription {
            get {
                return ResourceManager.GetString("LimitOptionsCharDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chars.
        /// </summary>
        internal static string LimitOptionsCharFormat {
            get {
                return ResourceManager.GetString("LimitOptionsCharFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max line limit:.
        /// </summary>
        internal static string LimitOptionsLineDescription {
            get {
                return ResourceManager.GetString("LimitOptionsLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lines.
        /// </summary>
        internal static string LimitOptionsLineFormat {
            get {
                return ResourceManager.GetString("LimitOptionsLineFormat", resourceCulture);
            }
        }
    }
}
