//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StyleCopPlus.Plugin.AdvancedNaming {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntitySettingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitySettingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StyleCopPlus.Plugin.AdvancedNaming.EntitySettings.EntitySettingResources", typeof(EntitySettingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot; Setting.
        /// </summary>
        internal static string EditorCaption {
            get {
                return ResourceManager.GetString("EditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage of @ character is prohibited.
        /// </summary>
        internal static string ExampleBlockAt {
            get {
                return ResourceManager.GetString("ExampleBlockAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short names (less than 4 characters) are prohibited.
        /// </summary>
        internal static string ExampleCheckLength {
            get {
                return ResourceManager.GetString("ExampleCheckLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage of non-English characters is prohibited.
        /// </summary>
        internal static string ExampleEnglishOnly {
            get {
                return ResourceManager.GetString("ExampleEnglishOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify where you would like to prohibit
        ///using @ character in name..
        /// </summary>
        internal static string HelpBlockAt {
            get {
                return ResourceManager.GetString("HelpBlockAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify where you would like to prohibit
        ///using short names (less than 4 characters)..
        /// </summary>
        internal static string HelpCheckLength {
            get {
                return ResourceManager.GetString("HelpCheckLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify where you would like to prohibit
        ///using non-English characters in names..
        /// </summary>
        internal static string HelpEnglishOnly {
            get {
                return ResourceManager.GetString("HelpEnglishOnly", resourceCulture);
            }
        }
    }
}
